/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutStagesRouteImport } from './routes/_pathlessLayout/stages'
import { Route as PathlessLayoutComboDataViewRouteImport } from './routes/_pathlessLayout/combo-data-view'
import { Route as PathlessLayoutComboControlRouteImport } from './routes/_pathlessLayout/combo-control'
import { Route as PathlessLayoutChopperwheelRouteImport } from './routes/_pathlessLayout/chopperwheel'
import { Route as PathlessLayoutElectrometerDeviceIdRouteImport } from './routes/_pathlessLayout/electrometer.$deviceId'
import { Route as PathlessLayoutElectrometerDeviceId1AndDeviceId2RouteImport } from './routes/_pathlessLayout/electrometer.$deviceId1.and.$deviceId2'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutStagesRoute = PathlessLayoutStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutComboDataViewRoute =
  PathlessLayoutComboDataViewRouteImport.update({
    id: '/combo-data-view',
    path: '/combo-data-view',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutComboControlRoute =
  PathlessLayoutComboControlRouteImport.update({
    id: '/combo-control',
    path: '/combo-control',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutChopperwheelRoute =
  PathlessLayoutChopperwheelRouteImport.update({
    id: '/chopperwheel',
    path: '/chopperwheel',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutElectrometerDeviceIdRoute =
  PathlessLayoutElectrometerDeviceIdRouteImport.update({
    id: '/electrometer/$deviceId',
    path: '/electrometer/$deviceId',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutElectrometerDeviceId1AndDeviceId2Route =
  PathlessLayoutElectrometerDeviceId1AndDeviceId2RouteImport.update({
    id: '/electrometer/$deviceId1/and/$deviceId2',
    path: '/electrometer/$deviceId1/and/$deviceId2',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/chopperwheel': typeof PathlessLayoutChopperwheelRoute
  '/combo-control': typeof PathlessLayoutComboControlRoute
  '/combo-data-view': typeof PathlessLayoutComboDataViewRoute
  '/stages': typeof PathlessLayoutStagesRoute
  '/': typeof PathlessLayoutIndexRoute
  '/electrometer/$deviceId': typeof PathlessLayoutElectrometerDeviceIdRoute
  '/electrometer/$deviceId1/and/$deviceId2': typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2Route
}
export interface FileRoutesByTo {
  '/chopperwheel': typeof PathlessLayoutChopperwheelRoute
  '/combo-control': typeof PathlessLayoutComboControlRoute
  '/combo-data-view': typeof PathlessLayoutComboDataViewRoute
  '/stages': typeof PathlessLayoutStagesRoute
  '/': typeof PathlessLayoutIndexRoute
  '/electrometer/$deviceId': typeof PathlessLayoutElectrometerDeviceIdRoute
  '/electrometer/$deviceId1/and/$deviceId2': typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/chopperwheel': typeof PathlessLayoutChopperwheelRoute
  '/_pathlessLayout/combo-control': typeof PathlessLayoutComboControlRoute
  '/_pathlessLayout/combo-data-view': typeof PathlessLayoutComboDataViewRoute
  '/_pathlessLayout/stages': typeof PathlessLayoutStagesRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/electrometer/$deviceId': typeof PathlessLayoutElectrometerDeviceIdRoute
  '/_pathlessLayout/electrometer/$deviceId1/and/$deviceId2': typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chopperwheel'
    | '/combo-control'
    | '/combo-data-view'
    | '/stages'
    | '/'
    | '/electrometer/$deviceId'
    | '/electrometer/$deviceId1/and/$deviceId2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chopperwheel'
    | '/combo-control'
    | '/combo-data-view'
    | '/stages'
    | '/'
    | '/electrometer/$deviceId'
    | '/electrometer/$deviceId1/and/$deviceId2'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/chopperwheel'
    | '/_pathlessLayout/combo-control'
    | '/_pathlessLayout/combo-data-view'
    | '/_pathlessLayout/stages'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/electrometer/$deviceId'
    | '/_pathlessLayout/electrometer/$deviceId1/and/$deviceId2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/stages': {
      id: '/_pathlessLayout/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof PathlessLayoutStagesRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/combo-data-view': {
      id: '/_pathlessLayout/combo-data-view'
      path: '/combo-data-view'
      fullPath: '/combo-data-view'
      preLoaderRoute: typeof PathlessLayoutComboDataViewRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/combo-control': {
      id: '/_pathlessLayout/combo-control'
      path: '/combo-control'
      fullPath: '/combo-control'
      preLoaderRoute: typeof PathlessLayoutComboControlRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/chopperwheel': {
      id: '/_pathlessLayout/chopperwheel'
      path: '/chopperwheel'
      fullPath: '/chopperwheel'
      preLoaderRoute: typeof PathlessLayoutChopperwheelRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/electrometer/$deviceId': {
      id: '/_pathlessLayout/electrometer/$deviceId'
      path: '/electrometer/$deviceId'
      fullPath: '/electrometer/$deviceId'
      preLoaderRoute: typeof PathlessLayoutElectrometerDeviceIdRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/electrometer/$deviceId1/and/$deviceId2': {
      id: '/_pathlessLayout/electrometer/$deviceId1/and/$deviceId2'
      path: '/electrometer/$deviceId1/and/$deviceId2'
      fullPath: '/electrometer/$deviceId1/and/$deviceId2'
      preLoaderRoute: typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2RouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutChopperwheelRoute: typeof PathlessLayoutChopperwheelRoute
  PathlessLayoutComboControlRoute: typeof PathlessLayoutComboControlRoute
  PathlessLayoutComboDataViewRoute: typeof PathlessLayoutComboDataViewRoute
  PathlessLayoutStagesRoute: typeof PathlessLayoutStagesRoute
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutElectrometerDeviceIdRoute: typeof PathlessLayoutElectrometerDeviceIdRoute
  PathlessLayoutElectrometerDeviceId1AndDeviceId2Route: typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2Route
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutChopperwheelRoute: PathlessLayoutChopperwheelRoute,
  PathlessLayoutComboControlRoute: PathlessLayoutComboControlRoute,
  PathlessLayoutComboDataViewRoute: PathlessLayoutComboDataViewRoute,
  PathlessLayoutStagesRoute: PathlessLayoutStagesRoute,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutElectrometerDeviceIdRoute:
    PathlessLayoutElectrometerDeviceIdRoute,
  PathlessLayoutElectrometerDeviceId1AndDeviceId2Route:
    PathlessLayoutElectrometerDeviceId1AndDeviceId2Route,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
