/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutElectrometerDeviceIdRouteImport } from './routes/_pathlessLayout/electrometer.$deviceId'
import { Route as PathlessLayoutElectrometerDeviceId1AndDeviceId2RouteImport } from './routes/_pathlessLayout/electrometer.$deviceId1.and.$deviceId2'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutElectrometerDeviceIdRoute =
  PathlessLayoutElectrometerDeviceIdRouteImport.update({
    id: '/electrometer/$deviceId',
    path: '/electrometer/$deviceId',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutElectrometerDeviceId1AndDeviceId2Route =
  PathlessLayoutElectrometerDeviceId1AndDeviceId2RouteImport.update({
    id: '/electrometer/$deviceId1/and/$deviceId2',
    path: '/electrometer/$deviceId1/and/$deviceId2',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PathlessLayoutIndexRoute
  '/electrometer/$deviceId': typeof PathlessLayoutElectrometerDeviceIdRoute
  '/electrometer/$deviceId1/and/$deviceId2': typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2Route
}
export interface FileRoutesByTo {
  '/': typeof PathlessLayoutIndexRoute
  '/electrometer/$deviceId': typeof PathlessLayoutElectrometerDeviceIdRoute
  '/electrometer/$deviceId1/and/$deviceId2': typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/electrometer/$deviceId': typeof PathlessLayoutElectrometerDeviceIdRoute
  '/_pathlessLayout/electrometer/$deviceId1/and/$deviceId2': typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/electrometer/$deviceId'
    | '/electrometer/$deviceId1/and/$deviceId2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/electrometer/$deviceId'
    | '/electrometer/$deviceId1/and/$deviceId2'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/electrometer/$deviceId'
    | '/_pathlessLayout/electrometer/$deviceId1/and/$deviceId2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/electrometer/$deviceId': {
      id: '/_pathlessLayout/electrometer/$deviceId'
      path: '/electrometer/$deviceId'
      fullPath: '/electrometer/$deviceId'
      preLoaderRoute: typeof PathlessLayoutElectrometerDeviceIdRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/electrometer/$deviceId1/and/$deviceId2': {
      id: '/_pathlessLayout/electrometer/$deviceId1/and/$deviceId2'
      path: '/electrometer/$deviceId1/and/$deviceId2'
      fullPath: '/electrometer/$deviceId1/and/$deviceId2'
      preLoaderRoute: typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2RouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutElectrometerDeviceIdRoute: typeof PathlessLayoutElectrometerDeviceIdRoute
  PathlessLayoutElectrometerDeviceId1AndDeviceId2Route: typeof PathlessLayoutElectrometerDeviceId1AndDeviceId2Route
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutElectrometerDeviceIdRoute:
    PathlessLayoutElectrometerDeviceIdRoute,
  PathlessLayoutElectrometerDeviceId1AndDeviceId2Route:
    PathlessLayoutElectrometerDeviceId1AndDeviceId2Route,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
